# app/config/security.yml
security:
    providers:
        in_memory:
            memory:
                users:
                    ryan:
                        password: ryanpass
                        roles: 'ROLE_ADMIN'
                    admin:
                        password: kitten
                        roles: 'ROLE_ADMIN'
                    anna_admin:
                        password: kitten
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            #http_basic: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: default_security_target
            logout:
                path:   /logout
                target: /
        
    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/*, role: ROLE_ADMIN }
     
       
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: bcrypt

   